### ISSUE TITLE
SQLite not ThreatSafe with ForEach -Parallel?

### ISSUE THREAD

**Issue by Gill-Bates** [mithrandyr/SimplySql#167]
I am using a SQlite Database and want to insert Items ForEach -Parallel.

For me it seems, the Module is not Threat Safe:

My Code:

```
$allItems | ForEach-Object -Parallel {
        Import-Module "SimplySql" -Force
        Open-SQLiteConnection -DataSource $using:database
        Invoke-SqlUpdate -Query $query
}
```

```
2024-09-06T10:52:09Z   [Error]   ERROR: An item with the same key has already been added. Key: default
Exception             : 
    Type       : System.ArgumentException
    Message    : An item with the same key has already been added. Key: default
    TargetSite : 
        Name          : ThrowAddingDuplicateWithKeyArgumentException
        DeclaringType : [System.ThrowHelper]
        MemberType    : Method
        Module        : System.Private.CoreLib.dll
    Source     : System.Private.CoreLib
    HResult    : -2147024809
    StackTrace : 
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at SimplySql.Engine.Logic.OpenAndAddConnection(baseConnectionDetail connDetail)
   at SimplySql.Cmdlets.OpenSQLiteConnection.ProcessRecord()
```
```
$PSVersionTable
Name                           Value
----                           -----
PSVersion                      7.4.5
PSEdition                      Core
GitCommitId                    7.4.5
OS                             Microsoft Windows 10.0.20348
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

`SimplySQL Version: 2.0.4.75`

**Comment by mithrandyr** [comment]
@Gill-Bates Yeah -- the module is probably not thread-safe... but your logic also wouldn't work (at least the way you are hoping).  When you use any of the `Open-*Connection` cmdlets, you are creating a connection to the database and that connection is stored at the PowerShell session level, i.e. it is globally available.  In order to open multiple connections, you **must** specify the `-ConnectionName` parameter in order to distinguish them.  If you do not specify this parameter, then connection will be opened as stored as "default".

```powershell
# this
Open-SQLiteConnection -ConnectionName default
# is functionally equivalent to this
Open-SQLiteConnection

# moreover, once you have opened a connection with a particular name, if you try to open a new connection using the same name, then the old connection will be CLOSED, a new connection will open and be associated to that name.
Open-SQLiteconnection
Show-SqlConnection # so you can see what it is
Open-SqlConnection localhost # opening a sql connection to the local host
Show-SqlConnection # ohh look, now its a MSSQL connection and not SQLite

# so then.. how do I open multiple connections?  using -ConnectionName
Open-SQLiteconnection -ConnectionName "a"
Open-SqlConnection localhost -ConnectionName "b" 
Show-SqlConnection a # to see SQLite
Show-SqlConnection b # to see MSSQL

# and if I want to interact with those connections, all the remaining cmdlets have a -ConnectionName parameter to determine which connection to use... and if you don't specify it, it will assume there is a "default" connection in existence.
# lets show all the Connection Names and then close all connections
Show-SqlConnection -All
Show-SqlConnection -All | Close-SqlConnection

# now lets demonstrate what happens if you don't consistently use -ConnectionName
Open-SQLiteConnection -CN "test" # -CN is the alias of the parameter -ConnectionName
Invoke-SqlQuery "Select 'Hi'"  # this will fail, it will respond with a "Connection 'default' does not exist"!
Invoke-SqlQuery "Select 'Hi'" -cn test # this will work.
Close-SqlConnection test
```

All of this to say, your `For-Each -Parallel {}` construct is opening a connection multiple times and setting it to the same connectionName.. and yes in a threading scenario, the module doesn't account for this and throws errors. -- Instead, what you would need to do is assign a unique connection name for each open and use that connection name.  Despite new runspaces being open -- the connection list for the Module is global for runspaces (probably a side effect of converting the module from script to binary).  So the solution will be to create unique ConnectionNames.
```powershell
$allItems | ForEach-Object -Parallel {
        Import-Module "SimplySql" -Force
        $cn = [guid]::NewGuid().ToString()
        Open-SQLiteConnection -DataSource $using:database -cn $cn
        Invoke-SqlUpdate -Query $query -cn $cn
        Close-SqlConnection -cn $cn
}
```

**Comment by mithrandyr** [comment]
@Gill-Bates  a follow-up, in version 2.0 the module moved from being a script module to a binary module, and the connections cache is now contained inside a DLL.  Because DLLs can only be loaded one per powershell session, they are available across all runspaces, which is why the connections are leaking across.  Again, using unique connection names for in your `foreach-parallel` should resolve -- were you able to confirm?

**Comment by Gill-Bates** [comment]
Thanks @mithrandyr ! I have solved it like you suggested!

```
$data | ForEach-Object -Parallel {

    [string]$dbSession = (New-Guid).Guid
    Open-SQLiteConnection -DataSource $using:database -ConnectionName $dbSession

    Invoke-SqlUpdate -cn $ConnectionName -Query ...

    Close-SqlConnection -ConnectionName $dbSession 
}
```
